AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  fristLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/firstLambda/index.handler
      Runtime: nodejs14.x
      CodeUri: s3://lambdacicdtest/4cfa785f594f9206fce51fbe4f602649
    Metadata:
      SamResourceId: fristLambda
  secondLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/secondLambda/index.handler
      Runtime: nodejs14.x
      CodeUri: s3://lambdacicdtest/4cfa785f594f9206fce51fbe4f602649
    Metadata:
      SamResourceId: secondLambda
