name: AWS SAM Deploy

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install SAM CLI
        run: npm install -g aws-sam-cli

      - name: Package and Deploy to AWS SAM
        run: |
          sam package --template-file template.yaml --s3-bucket your-s3-bucket-name --output-template-file packaged.yaml
          sam deploy --template-file packaged.yaml --stack-name your-stack-name --capabilities CAPABILITY_IAM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1  # e.g., us-east-1
